-- Semantic recipe search: a pgvector embedding per recipe + a similarity-match
-- RPC, so the Kitchen Concierge can rank across the WHOLE catalog by meaning
-- (not keyword/first-page sampling). Embeddings are generated by the open-source
-- `gte-small` model (384 dims) running natively in Supabase Edge Functions
-- (see supabase/functions/embed-recipes) — no external API, $0.

create extension if not exists vector;

-- 384-dim to match gte-small. Nullable: backfilled asynchronously by the
-- embed-recipes function; match_recipes ignores rows that aren't embedded yet.
alter table public.recipes add column if not exists embedding vector(384);

-- HNSW index for fast approximate nearest-neighbour on cosine distance. Cosine
-- (`vector_cosine_ops` / the `<=>` operator) because gte-small embeddings are
-- normalized, so cosine similarity is the right metric.
create index if not exists recipes_embedding_hnsw_idx
  on public.recipes using hnsw (embedding vector_cosine_ops);

-- Top-N most semantically-similar recipes to a query embedding, with an optional
-- tag filter. SECURITY INVOKER so it runs as the calling user and RLS applies
-- exactly as elsewhere (recipes are shared-readable by any authenticated user).
-- The vector search happens in the `top` CTE first (index-friendly: order by
-- `<=>` + limit) before joining tags, so the HNSW index is actually used.
create or replace function public.match_recipes(
  query_embedding vector(384),
  match_count int default 20,
  filter_tag text default null
) returns table (
  id bigint,
  title text,
  prep_time integer,
  servings integer,
  tags text[],
  similarity double precision
)
language sql
stable
security invoker
set search_path = public
as $$
  with top as (
    select r.id, r.title, r.prep_time, r.servings,
           r.embedding <=> query_embedding as distance
    from recipes r
    where r.embedding is not null
      and (
        filter_tag is null
        or exists (
          select 1 from recipe_tags rt2
          join tags t2 on t2.id = rt2.tag_id
          where rt2.recipe_id = r.id and t2.name = filter_tag
        )
      )
    order by r.embedding <=> query_embedding
    limit greatest(match_count, 1)
  )
  select top.id, top.title, top.prep_time, top.servings,
         coalesce(array_agg(distinct t.name) filter (where t.name is not null), '{}') as tags,
         1 - top.distance as similarity
  from top
  left join recipe_tags rt on rt.recipe_id = top.id
  left join tags t on t.id = rt.tag_id
  group by top.id, top.title, top.prep_time, top.servings, top.distance
  order by top.distance;
$$;

grant execute on function public.match_recipes(vector, int, text) to authenticated;

-- Lets the embed-recipes backfill (running with the service key) find work
-- efficiently: recipes still needing an embedding.
create index if not exists recipes_embedding_null_idx
  on public.recipes (id) where embedding is null;
